### ISSUE TITLE
[Question] - speed.pypy.org should show PyPy performance benchmark vs newer Python versions

### ISSUE THREAD

**Issue by yogevyuval** [pypy/pypy#4844]
Hi!

The performance information + benchmarks in the website are super useful.
However, they are done against python 3.7.6. Since them python 3.8 - 3.12 all improved python performance significantly with the "fast python" project.

Any plans on updating the benchmarks with new python versions?

**Comment by mattip** [comment]
This would require some level of sponsorship: either someone would need to do the work and I could mentor/merge the changes, or it could be done as a [consulting job](https://www.pypy.org/pypy-sponsors.html#pypy-consulting-work). I would suggest doing it as part of a general update to the speed.pypy.org site.

As described [here](https://speed.pypy.org/about/) the benchmarks have been run on the same setup since 2006. There has been some action lately in the [codespeed repo](https://github.com/python/codespeed/issues), but in general that code is due for a facelift and version update. That might include updating the benchmark suite: it would be nice to find some more representative benchmarks from projects using Python/PyPy

**Comment by mattip** [comment]
This might be a nice opportunity to update the benchmarking machine

**Comment by gkirchou** [comment]
Since I am curious about the benchmark result for Python3.13 (w/ JIT and w/ no-gil), so I found this issue.

> However, they are done against python 3.7.6. Since them python 3.8 - 3.12 all improved python performance significantly with the "fast python" project.

Not sure if I missed anything, as of today (2024-Dec-06), [speed.pypy.org](https://speed.pypy.org/timeline/#/?exe=21,22&base=2+3920&ben=grid&revs=50&equid=off&quarts=on&extr=on&env=3) can show the result for pypy3.11 and cpython3.12.4 for benchmarker. Those are probably the updated result they have.

**Comment by mattip** [comment]
Yes, CPython3.11, CPython3.12 benchmarks were run after this issue was opened. Also, note the "lastest" results are from PyPy 3.11.

**Comment by yogevyuval** [comment]
Thanks @mattip @gkirchou 
The main page still shows the 3.7 version comparison, which in this point in time is almost not relevant
<img width="842" alt="image" src="https://github.com/user-attachments/assets/5e46d980-9724-4801-8b7e-02aab5317e30" />

**Comment by mattip** [comment]
Done in https://github.com/python/codespeed/pull/55. This also exposed a seeming slowdown on PyPy3.11, but I think that is due to some change in the machine. You can see the jump [here in the float benchmark](https://speed.pypy.org/timeline/#/?exe=21,8&base=10+2622&ben=float&revs=50&equid=off&quarts=on&extr=on&env=3) where those commits didn't change anything connected to performance.

**Comment by mattip** [comment]
Blog post is in draft. Closing.
