### ISSUE TITLE
Checksum change for pypy3.9 and pypy3.10

### ISSUE THREAD

**Issue by p-linnane** [pypy/pypy#4919]
Hello 👋 . I'm a maintainer for the [Homebrew](https://brew.sh) project. While updating some resources in our `pypy` formulae, we noticed the checksums we had for pypy3.9 and pypy3.10 have changed. I'm just looking for confirmation that the files were intentionally changed, so that we can rule out any malicious tampering. Thanks!

pypy3.9: https://downloads.python.org/pypy/pypy3.9-v7.3.15-src.tar.bz2
Previous: `e42c16593dd2d8e30ffa6287660c6984562bf4e9f95e660706e16764dfec85a8`
Current: `6bb9537d85aa7ad13c0aad2e41ff7fd55080bc9b4d1361b8f502df51db816e18`

pypy3.10: https://downloads.python.org/pypy/pypy3.10-v7.3.15-src.tar.bz2
Previous: `48ce19ca7642131b8468ddfb7ef355f49952518702ab501e2c6b3d9b4eb09ad4`
Current: `837622130b36603a1893899bd9f529961a8e4a56c9eb67268d72ddf8920c9579`

**Comment by mattip** [comment]
The checksums [were modified](https://github.com/pypy/pypy.org/commit/cfe817f391dd5a539fa9757d70b51cfb418bb699) on Jan 15, a few hours after the release, because the files were not compressed, see https://github.com/pypy/pypy/issues/4861. The current ones you list are correct. Do you have some automation that grabbed the sources as they were released and missed the update?

**Comment by p-linnane** [comment]
Thank you for the confirmation. In this case, a user submitted PR's when the releases were made.
