### ISSUE TITLE
Windows: PyPy Interpreter raises ModuleNotFoundError if path to interpreter contains Umlaut

### ISSUE THREAD

**Issue by mwmattis** [pypy/pypy#5000]
As the title suggests, we run into a `ModuleNotFoundError` when the path to the interpreter contains an Umlaut or probably any non-ascii characters:

```
$ /d/python/ü/pypy3.10-v7.3.16-win64/pypy.exe
ModuleNotFoundError: No module named 'encodings'
debug: OperationError:
debug:  operror-type: ModuleNotFoundError
debug:  operror-value: No module named 'encodings'
```

- OS: Windows-10
- PyPy version: pypy3.10-v7.3.16-win64 (I have also tested older pypy versions with the same result)
- Installation: Extracted PyPy via [pypy3.10-v7.3.16-win64.zip](https://downloads.python.org/pypy/pypy3.10-v7.3.16-win64.zip)
- Env: My environment does not contain any Python related environment variables

Please let me know if there is more information needed.

Thanks in advance!

**Comment by devdanzin** [comment]
Thank you for the report. This is another instance of/related to #3890.

**Comment by inoa-jboliveira** [comment]
Hi, it seems to happen with any non ascii char. Such as `ã`

**Comment by inoa-jboliveira** [comment]
Relevant: I've been using [uv](https://github.com/astral-sh/uv) to install pypy automatically which uses AppData dir for current user which, in my case, has a tilde

**Comment by mattip** [comment]
Are you using some kind of bash shell? This does not look like the cmd.exe prompt or a windows path
```
$ /d/python/ü/pypy3.10-v7.3.16-win64/pypy.exe
```

**Comment by mattip** [comment]
Nvrmind, I can reproduce this in cmd.exe as well. It seems something is off with sys.path already in the bootstrap code in app_main

**Comment by mwmattis** [comment]
> Are you using some kind of bash shell? This does not look like the cmd.exe prompt or a windows path
> 
> ```
> $ /d/python/ü/pypy3.10-v7.3.16-win64/pypy.exe
> ```

Yes, I think it was the gitbash.

**Comment by mattip** [comment]
Adding some notes since this is pretty complicated. The [call to initstdio](https://github.com/pypy/pypy/blob/7802d0776064e3ad6406b22b34e6328917923aef/pypy/interpreter/app_main.py#L782) fails. At this point, printing `sys.path` shows that the ü gets converted to garbage, so the stdlib path is not in syspath and the `import encoding` in `initsdtio` fails. 

Now the sys.path is determined by [`resolvedirof()` call](https://github.com/pypy/pypy/blob/7802d0776064e3ad6406b22b34e6328917923aef/pypy/module/sys/initpath.py#L66) which returns a __unicode__ filename, not utf-8 encoded: printing `[ord(x) for x in dirname]` shows 252 for the "ü". But this is fed to `space.newfilename` in [pypy_find_stdlib](https://github.com/pypy/pypy/blob/7802d0776064e3ad6406b22b34e6328917923aef/pypy/module/sys/initpath.py#L259), which expects bytes (utf-8).

The real call is buried a bit, `resolvedirof` -> `rpath.rabspath` -> `_ntrabaspath` -> `rposix.getfullpathname` -> `win32traits.GetFullPathName`. The correct solution, as stated in #3890, is to get rid of win32traits, which tries to discern between `GetFullPathNameA` and `GetFullPathNameW` and only use the wide versions, with proper handling of utf-8 -> wchar and back. Maybe there is a quick fix somehow, but the systematic problem will still remain.

**Comment by mattip** [comment]
Unfortunately, even if I fix `resolvedirof()` to return a utf-8 encoded list of paths, things elsewhere go bad. I think the next problem is that importlib scans `sys.path` for the file, ends up seeing the utf-8 bytes but feeds that to some ascii-based windows interface and fails. Instead of calling `as_unicode` or `as_str`, all the path handling in win32traits should grow a `as_utf8` method that will use `rffi.utf82whcharp_ex` and `rffi.wcharp2utf8`

**Comment by mattip** [comment]
I thought I was making progress, but after the utf8-rposix branch something new is failing
```
d:\temp\אבג>pypy-c-jit-185311-854888815faf-win64\pypy
debug: OperationError:
debug:  operror-type: ValueError
debug:  operror-value: bad marshal data (string is not ascii)
```

Time to learn about how and why marshalling is marking the data as ascii when I think it should be utf-8.

**Comment by mattip** [comment]
Progress. PyPy 3.10 at d0419b45 can now run in a unicode directory, but it fails to call `subprocess.Popen([sys.executable, ...`. This is what I get:
```
>>>> subprocess.check_output([sys.executable, "-m", "sysconfig"])
debug: WARNING: Library path not found, using compiled-in sys.path, with
debug: WARNING: sys.prefix = 'd:\\pypy_stuff\\buildbot64\\slave\\pypy-c-jit-win-x86-64\\build'
debug: WARNING: Make sure the pypy3 binary is kept inside its tree of files.
debug: WARNING: It is ok to create a symlink to it from somewhere else.
debug: OperationError:
debug:  operror-type: AttributeError
debug:  operror-value: module 'sys' has no attribute 'base_prefix'
```

The unicode in `sys.executable` is messing something up, even though `os.path.exists(sys.executable)` is `True`. The console also does not know how to display the unicode. Instead of `אבג` I get `╫É╫æ╫Æ`, even though pypy app-level knows it is 3 unicode chars.

**Comment by mattip** [comment]
Passed the initpath hurdle in  6e7ee1615.
Next up is that `dlopen` should use wide interfaces, i.e. `LoadLibraryW`. Currently it is using `LoadLibraryA` which means cffi, ctypes, cpyext, and `cppyy` cannot load a DLL from a path with unicode. I might have also found the right point in `app_main` to add `encoding='utf-8'` to opening stdout, so the console will properly display unicode strings.

**Comment by mattip** [comment]
Solved in latest nightly.
