### ISSUE TITLE
`_cffi_ssl._stdssl._SSLSocket.do_handshake()` segfaults

### ISSUE THREAD

**Issue by devdanzin** [pypy/pypy#5124]
It's possible to segfault PyPy by creating an invalid `_cffi_ssl._stdssl._SSLSocket` and calling `do_handshake()` on it:

```python
Python 3.10.14 (6b367d9e6715, Nov 14 2024, 04:48:15)
[PyPy 7.3.18-alpha0 with GCC 10.2.1 20210130 (Red Hat 10.2.1-11)] on linux
>>>> import _cffi_ssl._stdssl
>>>> s = _cffi_ssl._stdssl._SSLSocket(1)
>>>> s.do_handshake()
Segmentation fault (core dumped)
```
Found using fusil by @vstinner.

**Comment by mattip** [comment]
CPython also segfaults with `cpython3.11 -c "import _ssl; s = _ssl._SSLSocket(); s.do_handshake()`. I think the check for a valid context should be done in a more general way since other functions could also be abused in this way. On CPython the place to do this is `GET_SOCKET`, in pypy I added a check to `get_socket_or_connection_gone` in 8ec6bc8c0
