### ISSUE TITLE
Changed error message in list.pop fails a Cython test

### ISSUE THREAD

**Issue by mattip** [pypy/pypy#5160]
In CPython and PyPy3.10 
```
>>>> a = [1, 2, 3]
>>>> a.pop(1, 2)
Traceback (most recent call last):
  File "<python-input-1>", line 1, in <module>
    a.pop(1,2,3)
TypeError: pop() takes from 1 to 2 positional arguments but 4 were given
```

Something changed in the error message for PyPy 3.11, it is now
```
TypeError: list.pop() takes from 1 to 2 positional arguments but 4 were given
```

Was that on purpose?

**Comment by cfbolz** [comment]
yeah, it was intentional. CPython is unfortunately super inconsistent about when to use the the qualname in error messages, and when to use only the method name. I did this change to fix other tests that were requiring the qualname.

I don't think it makes sense to try to chase the extremely weird specifics of cpy here. We might want to rather file bugs to cpython about this.

Imo the general principle that PyPy mostly follows about such cases is:

"When in doubt, built-in types should behave like the equivalent python code."

Maybe we should document this specifically? Some of the [misc](https://doc.pypy.org/en/latest/cpython_differences.html#miscellaneous) differences we document are specific instances of this principle.

for this specific bug the principle applies: if you write a python method with the same signature and pass too many arguments, you get the qualname in both cpython and pypy.

**Comment by mattip** [comment]
OK, I will suggest fixing the over-strict regex in cython.

**Comment by mattip** [comment]
Closing.
